[project]
name = "uv-pre-commit-reprod"
dynamic = ["version"]

[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "uv_pre_commit_reprod.__version__"}
